# Generated by Django 4.0.5 on 2023-02-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='localite',
            table='t_localite',
        ),
        migrations.AlterModelTable(
            name='pays',
            table='t_pays',
        ),
        migrations.AlterModelTable(
            name='typelocalite',
            table='t_type_localite',
        ),
    ]
