# Generated by Django 4.0.5 on 2023-02-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_parent_id_localite_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localite',
            name='parent',
        ),
    ]
