# Generated by Django 4.0.5 on 2023-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_localite_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localite',
            name='concat_parent_fils_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='localite',
            name='concat_parent_fils_string',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
