# Generated by Django 4.0.5 on 2023-02-11 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_alter_localite_concat_parent_fils_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=190, null=True)),
                ('logo', models.CharField(max_length=190, null=True)),
                ('slogan', models.TextField(null=True)),
                ('date_mise_a_jour', models.DateTimeField(null=True)),
                ('emails', models.CharField(max_length=1000, null=True)),
                ('telephones', models.CharField(max_length=1000, null=True)),
                ('cellulaires', models.CharField(max_length=1000, null=True)),
                ('reseaux_sociaux', models.CharField(max_length=1000, null=True)),
                ('est_personne', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_agence',
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_pieces', models.IntegerField()),
                ('superficie', models.FloatField(null=True)),
                ('coordonnees_gps', models.CharField(max_length=15)),
                ('prix', models.FloatField(null=True)),
                ('a_debattre', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('img_principal', models.ImageField(upload_to='catalog/maison/')),
                ('quartier', models.CharField(max_length=150)),
                ('secteur', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.agence')),
                ('localite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.localite')),
            ],
            options={
                'db_table': 't_maisons',
            },
        ),
        migrations.CreateModel(
            name='Modecommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 't_mode_commercial',
            },
        ),
        migrations.CreateModel(
            name='Typemaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='image/categorie')),
            ],
            options={
                'db_table': 't_type_maison',
            },
        ),
        migrations.CreateModel(
            name='Typestanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='image/standing')),
            ],
            options={
                'db_table': 't_type_standing',
            },
        ),
        migrations.CreateModel(
            name='Representant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.agence')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_representant',
            },
        ),
        migrations.CreateModel(
            name='Maisonimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='catalog/maison/')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.maison')),
            ],
            options={
                'db_table': 't_maison_image',
            },
        ),
        migrations.AddField(
            model_name='maison',
            name='mode_commercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.modecommercial'),
        ),
        migrations.AddField(
            model_name='maison',
            name='type_maison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.typemaison'),
        ),
        migrations.AddField(
            model_name='maison',
            name='type_standing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.typestanding'),
        ),
    ]
