# Generated by Django 4.0.5 on 2023-02-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_agence_maison_modecommercial_typemaison_typestanding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='secteur',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
