# Generated by Django 4.0.5 on 2023-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_maison_secteur_alter_maison_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='secteur',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
