# Generated by Django 4.0.5 on 2023-02-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_maison_secteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typemaisonpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('icons', models.ImageField(upload_to='icon/piece_maison/')),
            ],
        ),
        migrations.CreateModel(
            name='Maisonpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(null=True)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.maison')),
                ('type_piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.typemaisonpiece')),
            ],
        ),
    ]
