# Generated by Django 4.0.5 on 2023-02-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_typemaisonpiece_maisonpiece'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maisonpiece',
            table='t_maison_piece',
        ),
        migrations.AlterModelTable(
            name='typemaisonpiece',
            table='t_type_maison_piece',
        ),
    ]
